import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/theme/app_theme.dart';
import 'features/home/view/home_screen.dart';
import 'firebase_options.dart'; // File generated by flutterfire configure

void main() async {
  // Ensures that widget binding is initialized before calling platform-specific code
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the default options for the current platform
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    // ProviderScope is required to manage state across the app using Riverpod
    const ProviderScope(
      child: SerpilModaApp(),
    ),
  );
}

class SerpilModaApp extends StatelessWidget {
  const SerpilModaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Serpil Moda Evi',
      debugShowCheckedModeBanner: false,
      // Applying the custom luxury dark theme defined in AppTheme
      theme: AppTheme.luxuryTheme,
      home: const HomeScreen(),
    );
  }
}
